api:
  build: ./src/api
  volumes:
    - "./src/api:/usr/src/app"
  command: dumb-init npm run dev
  environment:
    VIRTUAL_HOST: visitapi.docker
    PORT: 5000
    NODE_ENV: development
  links:
    - mongo

api_test:
  build: ./src/api
  volumes:
    - "./src/api:/usr/src/app"
  command: dumb-init npm test
  environment:
    NODE_ENV: test

mongo:
  image: mongo:3.2